// client-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'hashtrack';
}

<main *ngIf="sessionStatus === 'logged-out'"
    class="uk-flex uk-flex-center uk-flex-middle uk-background-muted uk-height-viewport">
    <app-login (successfulLogin)="onLogin()"></app-login>
</main>

<main *ngIf="sessionStatus === 'pending'"
    class="uk-flex uk-flex-center uk-flex-middle uk-background-muted uk-height-viewport">
    <div uk-spinner="ratio: 5"></div>
</main>

<main *ngIf="sessionStatus === 'logged-in'"
    class="uk-flex uk-flex-center uk-background-muted uk-height-viewport">
    <app-board (logout)="onLogout()"></app-board>
</main>

<router-outlet></router-outlet>

// client/src/App.svelte
<script>
	import Login from './Login.svelte'
	import { getCurrentUser } from './lib/user'

	let sessionStatus = 'pending'
	checkStatus()

	async function checkStatus() {
		try {
			await getCurrentUser()
			sessionStatus = 'logged-in'
		} catch(error) {
			sessionStatus = 'logged-out'
		}
	}
</script>

<main class="uk-flex uk-flex-center uk-flex-middle uk-background-muted uk-height-viewport">
	{#if sessionStatus === 'pending'}
		<div uk-spinner="ratio: 5" />
	{:else if sessionStatus === 'logged-in'}
		<h1>Logged in!</h1>
	{:else}
		<Login/>
	{/if}
</main>
