// client-angular/src/app/tweet-list/tweet-list.component.ts
import { Component, OnInit } from '@angular/core';
import { Tweet, TweetService } from 'src/services/tweet.service';

@Component({
  selector: 'app-tweet-list',
  templateUrl: './tweet-list.component.html',
  styleUrls: ['./tweet-list.component.scss']
})
export class TweetListComponent implements OnInit {

  debounceTimeout = 500
  debounce?: any
  search = ''
  tweets?: Tweet[]

  constructor(
    private tweetService: TweetService
  ) { }

  ngOnInit(): void {
    this.refreshTweets()
  }

  async refreshTweets() {
    this.tweets = await this.tweetService.getLatest(this.search)
    this.tweetService.listen(this.search, tweet => {
      this.tweets = [tweet, ...this.tweets].slice(0, 50)
    })
  }

  async searchTweets() {
    clearTimeout(this.debounce)
    this.debounce = setTimeout(() => { this.refreshTweets() }, this.debounceTimeout)
  }
}

<div class="uk-margin uk-inline">
  <!-- <SearchIcon /> -->
  <input class="uk-input uk-form-width-medium" [(ngModel)]="search" (keydown)="searchTweets()" />
</div>

<app-empty-state-card *ngIf="!tweets">
  Loading...
</app-empty-state-card>

<app-empty-state-card *ngIf="tweets && !tweets.length">
  No tweets to display, try including a new hashtag
</app-empty-state-card>

<ng-container *ngFor="let tweet of (tweets || [])">
  <app-tweet-card [id]="tweet.id" [authorName]="tweet.authorName" [publishedAt]="tweet.publishedAt" [text]="tweet.text">
  </app-tweet-card>
</ng-container>

// client/src/TweetList.svelte
<script>
    import TweetCard from './TweetCard.svelte'
    import SearchIcon from './icons/SearchIcon.svelte'
    import EmptyStateCard from './EmptyStateCard.svelte'
    import { getTweets } from './lib/tweet'

    let tweets
    let debounce
    let search = ''

    refreshTweets()

    async function refreshTweets() {
        tweets = await getTweets(search)
    }

    async function searchTweets() {
        clearTimeout(debounce)
        debounce = setTimeout(() => { refreshTweets() }, 500)
    }
</script>

<div class="uk-margin uk-inline">
    <SearchIcon />
    <input
        class="uk-input uk-form-width-medium"
        bind:value={search}
        on:input={searchTweets}/>
</div>

{#if !tweets}
    <EmptyStateCard>Loading...</EmptyStateCard>
{:else if tweets.length === 0}
    <EmptyStateCard>
        No tweets to display, try including a new hashtag
    </EmptyStateCard>
{:else}
    {#each tweets as tweet (tweet.id)}
        <TweetCard {...tweet} />
    {/each}
{/if}
