// client/src/Login.svelte
<script>
    import { createEventDispatcher } from 'svelte'
    import UserIcon from "./icons/UserIcon.svelte"
    import LockIcon from "./icons/LockIcon.svelte"
    import MailIcon from "./icons/MailIcon.svelte"
    import { login } from './lib/session'
    import { createUser } from './lib/user'

    let name
    let email
    let password
    let errorMessage
    let isAccountCreation = false

    const dispatch = createEventDispatcher()

    async function onConfirm() {
        errorMessage = undefined
        try {
            if (isAccountCreation) {
                await createUser(name, email, password)
            }   
            const session = await login(email, password)
            dispatch('sessionCreated', session)
        } catch (error) {
            errorMessage = error.message
        }
    }

    function onSwitch() {
        isAccountCreation = !isAccountCreation
        errorMessage = undefined
    }
</script>

<div class="uk-width-medium uk-padding-small">
    <fieldset class="uk-fieldset">
        {#if isAccountCreation}
            <div class="uk-margin-small">
                <div class="uk-inline uk-width-1-1">
                    <UserIcon />
                    <input
                        class="uk-input uk-border-pill"
                        placeholder="Name"
                        type="text"
                        bind:value={name} />
                </div>
            </div>
        {/if}
        <div class="uk-margin-small">
            <div class="uk-inline uk-width-1-1">
                <MailIcon />
                <input
                    class="uk-input uk-border-pill"
                    placeholder="Email"
                    type="email"
                    bind:value={email} />
            </div>
        </div>
        <div class="uk-margin-small">
            <div class="uk-inline uk-width-1-1">
                <LockIcon />
                <input
                    class="uk-input uk-border-pill"
                    placeholder="Password"
                    type="password"
                    bind:value={password} />
            </div>
        </div>
        <div class="uk-margin-bottom">
            <button
                on:click={onConfirm}
                class="uk-button uk-button-primary uk-width-1-1">
                {#if isAccountCreation}
                    CREATE ACCOUNT
                {:else}
                    LOG IN
                {/if}
            </button>
        </div>
        <div class="uk-text-center uk-margin-bottom">
            <a 
                href="javascript:void(0);"
                on:click={onSwitch}
                class="uk-link-muted uk-width-1-1">
                {#if isAccountCreation}
                    Go to login
                {:else}
                    I don't have an account
                {/if}
            </a>
        </div>
        {#if errorMessage}
            <div class="uk-alert-warning uk-text-center">
                {errorMessage}
            </div>
        {/if}
    </fieldset>
</div>

// client-angular/src/app/login/login.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { SessionService } from 'src/services/session.service';
import { UserService } from 'src/services/user.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  isAccountCreation: boolean
  actionText: string
  secondaryActionText: string
  errorMessage?: string

  name = ''
  email = ''
  password = ''

  @Output()
  successfulLogin = new EventEmitter<void>()

  constructor(private sessionService: SessionService, private userService: UserService) {
    this.isAccountCreation = false
    this.switchToLogin()
  }

  ngOnInit(): void { }

  onSwitch() {
    if (this.isAccountCreation) {
      this.isAccountCreation = false
      return this.switchToLogin()
    }
    this.isAccountCreation = true
    return this.switchToAccountCreation()
  }

  async onConfirm() {
    this.errorMessage = null
    if (this.isAccountCreation) {
      try {
        await this.createAccount()
      } catch (error) {
        this.errorMessage = error.message
        return
      }
    }

    try {
      await this.login()
    } catch (error) {
      this.errorMessage = error.message
    }
  }

  private async login() {
    const token = await this.sessionService.create(this.email, this.password)
    this.successfulLogin.emit()
  }

  private async createAccount() {
    const user = await this.userService.create(this.name, this.email, this.password)
  }

  private switchToAccountCreation() {
    this.actionText = "CREATE ACCOUNT"
    this.secondaryActionText = "Go to login"
  }

  private switchToLogin() {
    this.actionText = "LOGIN"
    this.secondaryActionText = "I don't have an account"
  }

}

<div class="uk-width-medium uk-padding-small">
    <fieldset class="uk-fieldset">
        <div *ngIf="isAccountCreation" class="uk-margin-small">
            <div class="uk-inline uk-width-1-1">
                <!-- <UserIcon /> -->
                <input [(ngModel)]="name" class="uk-input uk-border-pill" placeholder="Name" type="text" />
            </div>
        </div>
        <div class="uk-margin-small">
            <div class="uk-inline uk-width-1-1">
                <!-- <MailIcon /> -->
                <input [(ngModel)]="email" class="uk-input uk-border-pill" placeholder="Email" type="email" />
            </div>
        </div>
        <div class="uk-margin-small">
            <div class="uk-inline uk-width-1-1">
                <!-- <LockIcon /> -->
                <input [(ngModel)]="password" class="uk-input uk-border-pill" placeholder="Password" type="password" />
            </div>
        </div>
        <div class="uk-margin-bottom">
            <button (click)="onConfirm()" class="uk-button uk-button-primary uk-width-1-1">
                {{actionText}}
            </button>
        </div>
        <div class="uk-text-center uk-margin-bottom">
            <a (click)="onSwitch()" class="uk-link-muted uk-width-1-1">
                {{secondaryActionText}}
            </a>
        </div>
        <div *ngIf="errorMessage" class="uk-alert-warning uk-text-center">
            {{errorMessage}}
        </div>
    </fieldset>
</div>
