// client/src/HashtagList.svelte
<script>
    import EmptyStateCard from './EmptyStateCard.svelte'
    import { getTracks, createTrack, removeTrack } from './lib/track'

    let tracks
    let hashtagName
    refreshTracks()

    const suggestions = [
        '#Svelte', '#NodeJs', '#TypeScript', '#Terraform', '#NPM', '#RollupJS',
        '#FullStack', '#PostgreSQL'
    ]
    const selectedSuggestion = suggestions[
        Math.floor(Math.random() * suggestions.length)
    ]

    async function refreshTracks() {
        tracks = await getTracks()
    }

    async function track() {
        const name = hashtagName
        hashtagName = ''
        const createdTrack = await createTrack(name)
        tracks = [...tracks, createdTrack]
    }

    async function untrack(name) {
        await removeTrack(name)
        tracks = tracks.filter(({ hashtagName }) => hashtagName !== name)
    }

    async function onTrackInput({ keyCode }) {
        if (keyCode === 13 && hashtagName) {
            await track()
        }
    }
</script>

<div class="uk-margin" uk-margin>
    <input 
        class="uk-input uk-form-width-medium" 
        placeholder="{selectedSuggestion}"
        type="text"
        on:keyup={onTrackInput}
        bind:value={hashtagName}>
    <button 
        class="uk-button uk-button-primary"
        on:click={track}
        disabled={!hashtagName}>
        Track
    </button>
</div>

{#if !tracks}
    <EmptyStateCard>Loading...</EmptyStateCard>
{:else if tracks.length === 0}
    <EmptyStateCard>
        You are not tracking any hashtags at the moment...
    </EmptyStateCard>
{:else}
    <div class="uk-flex uk-flex-wrap uk-flex-wrap-around">
        {#each tracks as track (track.hashtagName)}
            <div 
                class="uk-card uk-card-default uk-card-body uk-card-small card"
                on:click={() => untrack(track.hashtagName)}>
                {track.prettyName}
            </div>
        {/each}
    </div>
{/if}

<style>
    .card {
        margin: 0.1em;
    }
    .card:hover {
        text-decoration: line-through;
        opacity: 0.5;
        transition: opacity 0.1s ease-in-out;
        cursor: pointer;
    }
</style>

// client-angular/src/app/hashtag-list/hashtag-list.component.ts
import { Component, OnInit } from '@angular/core';
import { TrackService, Track } from 'src/services/track.service';

@Component({
  selector: 'app-hashtag-list',
  templateUrl: './hashtag-list.component.html',
  styleUrls: ['./hashtag-list.component.scss']
})
export class HashtagListComponent implements OnInit {

  hashtagName = ''
  selectedSuggestion: string
  tracks?: Track[]

  constructor(
    private trackService: TrackService
  ) {
    const suggestions = [
      '#Svelte', '#NodeJs', '#TypeScript', '#Terraform', '#NPM', '#RollupJS',
      '#FullStack', '#PostgreSQL'
    ]
    this.selectedSuggestion = suggestions[
      Math.floor(Math.random() * suggestions.length)
    ]
  }

  ngOnInit(): void {
    this.getTracks()
  }

  async getTracks() {
    this.tracks = await this.trackService.getAll()
  }

  async track() {
    const track = await this.trackService.create(this.hashtagName)
    this.tracks?.push(track)
  }

  async untrack(name: string) {
    const removedTrack = await this.trackService.remove(name)
    this.tracks = this.tracks
      ?.filter(track => track.hashtagName !== removedTrack.hashtagName)
  }

}

<div class="uk-margin" uk-margin>
    <input class="uk-input uk-form-width-medium" placeholder="{{selectedSuggestion}}" type="text"
        [(ngModel)]="hashtagName" on:keyup={onTrackInput}>
    <button class="uk-button uk-button-primary" (click)="track()" ng-disabled="!hashtagName">
        Track
    </button>
</div>

<app-empty-state-card *ngIf="!tracks">
    Loading...
</app-empty-state-card>

<app-empty-state-card *ngIf="tracks && !tracks.length">
    You are not tracking any hashtags at the moment...
</app-empty-state-card>

<div *ngIf="tracks?.length" class="uk-flex uk-flex-wrap uk-flex-wrap-around">
    <div *ngFor="let track of tracks" class="uk-card uk-card-default uk-card-body uk-card-small card"
        (click)="untrack(track.hashtagName)">
        {{track.prettyName}}
    </div>
</div>
