// client/src/TweetCard.svelte
<script>
    import { format } from 'timeago.js'

    export let id
    export let text
    export let authorName
    export let publishedAt

    let relativeDate = format(new Date(publishedAt), 'en_US')

    setInterval(() => {
        relativeDate = format(new Date(publishedAt), 'en_US')
    }, 1000);

    function open() {
        window.open(`https://twitter.com/${authorName}/status/${id}`, '_blank')
    }
</script>

<div 
    class="uk-card uk-card-default uk-card-body uk-margin-bottom uk-card-hover"
    on:click={open}>
    <p>
        <b>@{authorName}</b> 
        - {text} <span class="uk-text-muted">{relativeDate}</span>
    </p>
</div>

// client-angular/src/app/tweet-card/tweet-card.component.ts
import { Component, OnInit, Input } from '@angular/core';
import he from 'he'
import { format } from '../../lib/timeago'

@Component({
  selector: 'app-tweet-card',
  templateUrl: './tweet-card.component.html',
  styleUrls: ['./tweet-card.component.scss']
})
export class TweetCardComponent implements OnInit {

  @Input() authorName: string
  @Input() text: string
  @Input() publishedAt: string
  @Input() id: string
  decodedText: string
  relativeDate: string

  ngOnInit(): void {
    this.decodedText = he.decode(this.text)
    this.relativeDate = format(new Date(this.publishedAt), 'en_US')
    setInterval(() => {
      this.relativeDate = format(new Date(this.publishedAt), 'en_US')
    }, 10000);
  }

  open() {
    window.open(`https://twitter.com/${this.authorName}/status/${this.id}`, '_blank')
  }

}

<div class="uk-card uk-card-default uk-card-body uk-margin-bottom uk-card-hover" (click)="open()">
  <p>
    <b>{{authorName}}</b>
    - {{decodedText}}
    <span class="uk-text-small uk-text-muted uk-text-nowrap date-hint">
      {{relativeDate}}
    </span>
  </p>
</div>
