// client/src/Board.svelte
<script>
    import { createEventDispatcher } from "svelte";
    import TweetList from "./TweetList.svelte";
    import HashtagList from "./HashtagList.svelte";

    let tab = 'tweets'

    const dispatch = createEventDispatcher();

    function onLogout() {
        dispatch("sessionDestroyed", { token: undefined });
    }

    function setTab(id) {
        tab = id
    }
</script>

<div class="uk-width-xlarge uk-margin-top">
    <nav class="uk-navbar-container" uk-navbar>
        <div class="uk-navbar-left">
            <ul class="uk-navbar-nav">
                <li class={tab === 'tweets' ? 'uk-active' : ''}>
                    <a 
                        href="javascript:void(0);"
                        on:click={() => setTab('tweets')}>
                        Tweets
                    </a>
                </li>
                <li class={tab === 'hashtags' ? 'uk-active' : ''}>
                    <a 
                        href="javascript:void(0);"
                        on:click={() => setTab('hashtags')}>
                        Hashstags
                    </a>
                </li>
            </ul>
        </div>
        <div class="uk-navbar-right">
            <ul class="uk-navbar-nav">
                <li>
                    <a 
                        href="javascript:void(0);"
                        on:click={onLogout}>
                        Logout
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    {#if tab === 'tweets'}
        <TweetList/>
    {:else}
        <HashtagList/>
    {/if}
</div>

// client-angular/src/app/board/board.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';

type BoardTab = 'tweets' | 'hashtags'

@Component({
  selector: 'app-board',
  templateUrl: './board.component.html'
})
export class BoardComponent implements OnInit {

  tab: BoardTab
  
  @Output()
  logout = new EventEmitter<void>()

  constructor() {
    this.tab = 'tweets'
  }

  ngOnInit(): void {
  }

  setTab(tab: BoardTab) {
    this.tab = tab
  }

  onLogout() {
    this.logout.emit()
  }

}

<div class="uk-width-xlarge uk-margin-top">
    <nav class="uk-navbar-container" uk-navbar>
        <div class="uk-navbar-left">
            <ul class="uk-navbar-nav">
                <li [class]="tab === 'tweets' ? 'uk-active' : ''">
                    <a (click)="setTab('tweets')">
                        Tweets
                    </a>
                </li>
                <li [class]="tab === 'hashtags' ? 'uk-active' : ''">
                    <a (click)="setTab('hashtags')">
                        Hashstags
                    </a>
                </li>
            </ul>
        </div>
        <div class="uk-navbar-right">
            <ul class="uk-navbar-nav">
                <li>
                    <a (click)="onLogout()">
                        Logout
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <app-tweet-list *ngIf="tab === 'tweets'"></app-tweet-list>
    <app-hashtag-list *ngIf="tab === 'hashtags'"></app-hashtag-list>
</div>
